import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fitsy - store your favorites products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">{children}</html>;
}
