import type { Metadata } from "next";
import "./globals.css";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Testing nextjs",
  description: "Generated by create next app",
};

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between p-4 text-xl font-semibold border-b">
      <div className="font-bold uppercase">Fitsy</div>
      <div>
        <Button>Sign in</Button>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col gap-8 mb-8">
        <TopNav />
        <div className="px-24">{children}</div>
      </body>
    </html>
  );
}
